---
#tasks file for installjava
- name: Update all Ubuntu packages 
  become: true
  become_method: "sudo"
  apt:
    upgrade: "dist"
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: Install java for Ubuntu 
  become: true
  become_method: "sudo"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-8-jdk
  when: ansible_distribution == 'Ubuntu' 

- name: Install javaruntime
  chocolatey.chocolatey.win_chocolatey:
    name: javaruntime
    version: '8.0.231'
    state: present
  when: ansible_os_family == 'Windows'